stages:
  - test
  - package

test-qvm-lib:
  stage: test
  tags:
    - github
  only:
    - branches
  image:
    name: rigetti/quilc
    entrypoint: [""]
  script:
    - make dump-version-info
    - make test-lib DISABLE_SHARED_MEMORY_QVM_TESTS=1 RIGETTI_LISP_LIBRARY_HOME=/src

test-qvm-app:
  stage: test
  tags:
    - github
  only:
    - branches
  image:
    name: rigetti/quilc
    entrypoint: [""]
  script:
    - make dump-version-info
    - make test-app RIGETTI_LISP_LIBRARY_HOME=/src

docker-master:
  stage: package
  tags:
    - dockerd
    - github
  only:
    - master
  image: docker:stable
  script:
    - docker build --tag rigetti/qvm:${CI_COMMIT_SHORT_SHA} --tag rigetti/qvm:latest .
    - echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
    - docker push rigetti/qvm && docker rmi -f rigetti/qvm:latest

docker-branch:
  stage: package
  tags:
    - dockerd
    - github
  only:
    - branches
  except:
    - master
  image: docker:stable
  script:
    - docker build --tag rigetti/qvm:${CI_COMMIT_REF_SLUG} .
    - echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
    - docker push rigetti/qvm && docker rmi -f rigetti/qvm:${CI_COMMIT_REF_SLUG}

docker-vtag:
  stage: package
  tags:
    - dockerd
    - github
  # matches only on tags of the form vX.Y.Z
  only:
    - /^v(\d+\.)?(\d+\.)?(\d+)$/
  except:
    - branches
  image: docker:stable
  script:
    - docker build --tag rigetti/qvm:${CI_COMMIT_TAG} --tag rigetti/qvm:stable .
    - echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
    - docker push rigetti/qvm && docker rmi -f rigetti/qvm:stable
