include:
  - project: rigetti/ci
    file: pipelines/docker.gitlab-ci.yml

variables:
  IMAGE: rigetti/qvm

test-qvm-lib:
  stage: test
  tags:
    - github
  only:
    - branches
  image:
    name: rigetti/quilc
    entrypoint: [""]
  script:
    - make dump-version-info
    - make test-lib DISABLE_SHARED_MEMORY_QVM_TESTS=1 RIGETTI_LISP_LIBRARY_HOME=/src

test-qvm-app:
  stage: test
  tags:
    - github
  only:
    - branches
  image:
    name: rigetti/quilc
    entrypoint: [""]
  script:
    - make dump-version-info
    - make test-app RIGETTI_LISP_LIBRARY_HOME=/src
