###############################################################################
# qvm-tests docker image
###############################################################################
FROM qvm-base

# executed on docker run
WORKDIR /src/qvm
ENTRYPOINT ["make", "test"]
