###############################################################################
# qvm-base docker image
###############################################################################
FROM rigetticomputing/lisp-base:qcs-1.2.0

# organize the source
ADD cl-quil /src/cl-quil
ADD qvm /src/qvm

ARG build_target

# build QVM-APP (needs git)
WORKDIR /src/qvm
RUN make ${build_target}
