###############################################################################
# qvm-app-base docker image
###############################################################################
FROM rigetticomputing/lisp-base

# organize the source
# NOTE: only works if magicl, cl-quil, and qvm are in the same directory
ADD magicl /src/magicl
ADD cl-quil /src/cl-quil
ADD qvm /src/qvm

ARG build_target

# build QVM-APP (needs git)
WORKDIR /src/qvm
RUN make ${build_target}
